"HoleDiameter"=67.5
"HoleDiameterError"=1
"InsertInletDiameter"="HoleDiameter" - "HoleDiameterError"
"InsertRimWidth"=5
"InsertInletThickness"=6
"InsertInletHeight"=12.5
"CapRimWidth"=2
"CapRimThickness"=1.2
"InsertRimThickness"=0.4
"D7@Эскиз1"="CapDepth"
"JunctionDiameter"="InsertInletDiameter" - "InsertInletThickness"
"CapDepth"=("InsertRimThickness"+"InsertInletHeight")*0.7
"D1@Эскиз1"="CapRimWidth"
"D2@Эскиз7"="DriverSlotsDistance"/2
"D1@Эскиз9"="DriverSlotsDistance"/2
"DriverSlotsDistance"=40
"RimJunctionError"=0.8
"ThreadJunctionError"=0.4
"D3@Эскиз1"="ThreadJunctionError"
